title: processing-python-quad
hero_image: images/banner.png
description: processing-python-quad description
version: 4
listed: false
copyedit: false
last_tested: "2022-01-24"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
