---
title: Dessiner un quadrilatère
hero_image: images/banner.png
description: description traitement-python-quad
version: 4
listed: false
copyedit: false
last_tested: "2022-01-24"
steps:
  - title: Introduction
